### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by enbyspiders** [voec/melonpoop#1]
### high:
- [x] score count
- [x] restart level
- [x] snakesnakesnaken
- [x] collision
- [x] more seed
- [x] intro
- [x] music!
- [x] sfx
- [x] controller support
- [x] rotate objects around melon

### low:
- [x] pixelize tweemoji img
- [x] bubble second line
- [x] clouds bird + ballon
- [x] change bakcground color on klick
- [x] credits klick
- [x] skip end score
- [x] angry bubble text (other types?)
- [x] random score popups (+ melon!  // hot!-peperoni)
- [x] ~~ahk remove unneeded emoji~~
- [x] ~~test if all emoji work~~
- [x] puff away snake when lost

### bug:
- [x] bubble more dynamic, more than once
